networks:
  smartmes:
    driver: bridge

services:
  db:
    image: mysql:8.0.20
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: db_smartmes
      TZ: America/Belem
    networks:
      - smartmes
    volumes:
      - "./data:/docker-entrypoint-initdb.d/"

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    networks:
      - smartmes

  app-manufacturing:
    build:
      context: ./backend/apps/manufacturing-api
      dockerfile: Dockerfile
    image: smartmes-manufacturing
    container_name: smartmes-manufacturing
    networks:
      - smartmes
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=default
      - DB_HOST=db
    ports:
      - "8080:8080"
    privileged: true
    depends_on:
      - db

  app-maintenance:
    build:
      context: ./backend/apps/maintenance-api
      dockerfile: Dockerfile
    image: smartmes-maintenance
    container_name: smartmes-maintenance
    networks:
      - smartmes
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=default
      - DB_HOST=db
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "8081:8081"
    privileged: true
    depends_on:
      - db
      - rabbitmq
      - app-manufacturing
