server:
  port: 8081
  servlet:
    context-path: /maintenance-api

spring:
  application:
    name: smartmes.maintenance
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    database: ${DB_NAME:db_smartmes}
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:db_smartmes}?useTimezone=true&serverTimezone=America/Belem&createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASS:toor}
    hikari:
      pool-name: HikariCP
      minimum-idle: 5
      maximum-pool-size: 30
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  transaction:
    default-timeout: 120
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

queue:
  incident:
    name: maintenance.order.incident

logging.level:
  org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE